const data = [
  {
    slides: 1,
    slidetab: 1,
    slidephone: 1,
    css: "",
    images: ["asset/slider.png", "asset/slider.png", "asset/slider.png"],
  },
  {
    slides: 6,
    slidetab: 4,
    slidephone: 3,
    css: "css",
    images: [
      "asset/slider1.png",
      "asset/slider2.png",
      "asset/slider3.png",
      "asset/slider4.png",
      "asset/slider5.png",
      "asset/slider6.png",
      "asset/slider3.png",
      "asset/slider5.png",
    ],
  },
  {
    slides: 4,
    slidetab: 3,
    slidephone: 2,
    css: "css",
    images: [
      "asset/slider1.png",
      "asset/slider2.png",
      "asset/slider3.png",
      "asset/slider4.png",
      "asset/slider5.png",
      "asset/slider6.png",
      "asset/slider3.png",
      "asset/slider5.png",
    ],
  },
  {
    slides: 4,
    slidetab: 3,
    slidephone: 2,
    css: "css",
    images: [
      "asset/slider1.png",
      "asset/slider2.png",
      "asset/slider3.png",
      "asset/slider4.png",
      "asset/slider5.png",
      "asset/slider6.png",
      "asset/slider3.png",
      "asset/slider5.png",
    ],
  },
  {
    slides: 5.5,
    slidetab: 3,
    slidephone: 2,
    css: "css",
    images: [
      "asset/slider1.png",
      "asset/slider2.png",
      "asset/slider3.png",
      "asset/slider4.png",
      "asset/slider5.png",
      "asset/slider6.png",
      "asset/slider3.png",
      "asset/slider5.png",
    ],
  },
];

export { data };
